// import { Accommodation, Place } from "@/types";
// import { calculatePercentage } from "./utils";

// // Sample data
// export const PLACES: Place[] = [
//   {
//     id: "serengeti",
//     name: "Serengeti National Park",
//     description:
//       "Famous for the annual wildebeest migration and abundant wildlife",
//     activities: [
//       {
//         id: "serengeti-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive with experienced guide",
//         highSeasonCost: calculatePercentage("70+18%"),
//         lowSeasonCost: calculatePercentage("30+18%"),
//         childHighSeasonCost: calculatePercentage("20+18%"),
//         childLowSeasonCost: calculatePercentage("10+18%"),
//       },
//       {
//         id: "serengeti-balloon",
//         name: "Hot Air Balloon Safari",
//         description: "Sunrise hot air balloon ride over the plains",
//         highSeasonCost: 550,
//         lowSeasonCost: 450,
//         childHighSeasonCost: 275,
//         childLowSeasonCost: 225,
//       },
//       {
//         id: "serengeti-walking",
//         name: "Walking Safari",
//         description: "Guided walking safari with armed ranger",
//         highSeasonCost: 80,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//     ],
//   },
//   {
//     id: "masai-mara",
//     name: "Masai Mara National Reserve",
//     description:
//       "Famous for the annual wildebeest migration and abundant wildlife",
//     activities: [
//       {
//         id: "masai-mara-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive with experienced guide",
//         highSeasonCost: 200,
//         lowSeasonCost: 100,
//         childHighSeasonCost: 100,
//         childLowSeasonCost: 50,
//       },
//       {
//         id: "masai-mara-balloon",
//         name: "Hot Air Balloon Safari",
//         description: "Sunrise hot air balloon ride over the plains",
//         highSeasonCost: 550,
//         lowSeasonCost: 450,
//         childHighSeasonCost: 275,
//         childLowSeasonCost: 225,
//       },
//       {
//         id: "masai-mara-walking",
//         name: "Walking Safari",
//         description: "Guided walking safari with armed ranger",
//         highSeasonCost: 80,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//     ],
//   },
//   {
//     id: "lake-nakuru",
//     name: "Lake Nakuru National Park",
//     description:
//       "Famous for the annual wildebeest migration and abundant wildlife",
//     activities: [
//       {
//         id: "lake-nakuru-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive with experienced guide",
//         highSeasonCost: 60,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 30,
//         childLowSeasonCost: 30,
//       },
//       {
//         id: "lake-nakuru-balloon",
//         name: "Hot Air Balloon Safari",
//         description: "Sunrise hot air balloon ride over the plains",
//         highSeasonCost: 550,
//         lowSeasonCost: 450,
//         childHighSeasonCost: 275,
//         childLowSeasonCost: 225,
//       },
//       {
//         id: "lake-nakuru-walking",
//         name: "Walking Safari",
//         description: "Guided walking safari with armed ranger",
//         highSeasonCost: 80,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//     ],
//   },

//   {
//     id: "lake-naivasha",
//     name: "Lake Naivasha National Park",
//     description:
//       "Famous for the annual wildebeest migration and abundant wildlife",
//     activities: [
//       {
//         id: "lake-naivasha-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive with experienced guide",
//         highSeasonCost: 26,
//         lowSeasonCost: 26,
//         childHighSeasonCost: 13,
//         childLowSeasonCost: 13,
//       },
//       {
//         id: "lake-naivasha-balloon",
//         name: "Hot Air Balloon Safari",
//         description: "Sunrise hot air balloon ride over the plains",
//         highSeasonCost: 550,
//         lowSeasonCost: 450,
//         childHighSeasonCost: 275,
//         childLowSeasonCost: 225,
//       },
//       {
//         id: "lake-naivasha-walking",
//         name: "Walking Safari",
//         description: "Guided walking safari with armed ranger",
//         highSeasonCost: 80,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//     ],
//   },

//   {
//     id: "amboseli",
//     name: "Amboseli National Park",
//     description:
//       "Famous for the annual wildebeest migration and abundant wildlife",
//     activities: [
//       {
//         id: "amboseli-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive with experienced guide",
//         highSeasonCost: 60,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 30,
//         childLowSeasonCost: 30,
//       },
//       {
//         id: "amboseli-balloon",
//         name: "Hot Air Balloon Safari",
//         description: "Sunrise hot air balloon ride over the plains",
//         highSeasonCost: 550,
//         lowSeasonCost: 450,
//         childHighSeasonCost: 275,
//         childLowSeasonCost: 225,
//       },
//       {
//         id: "amboseli-walking",
//         name: "Walking Safari",
//         description: "Guided walking safari with armed ranger",
//         highSeasonCost: 80,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//     ],
//   },

//   {
//     id: "nyerere",
//     name: "Nyerere National Park",
//     description:
//       "Famous for the annual wildebeest migration and abundant wildlife",
//     activities: [
//       {
//         id: "nyerere-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive with experienced guide",
//         highSeasonCost: calculatePercentage("70+18%"),
//         lowSeasonCost: calculatePercentage("70+18%"),
//         childHighSeasonCost: calculatePercentage("35+18%"),
//         childLowSeasonCost: calculatePercentage("35+18%"),
//       },
//       {
//         id: "nyerere-balloon",
//         name: "Hot Air Balloon Safari",
//         description: "Sunrise hot air balloon ride over the plains",
//         highSeasonCost: 550,
//         lowSeasonCost: 450,
//         childHighSeasonCost: 275,
//         childLowSeasonCost: 225,
//       },
//       {
//         id: "nyerere-walking",
//         name: "Walking Safari",
//         description: "Guided walking safari with armed ranger",
//         highSeasonCost: 80,
//         lowSeasonCost: 60,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//     ],
//   },
//   {
//     id: "ngorongoro",
//     name: "Ngorongoro Crater",
//     description:
//       "UNESCO World Heritage site with incredible density of wildlife",
//     activities: [
//       {
//         id: "ngorongoro-crater-tour",
//         name: "Crater Floor Tour",
//         description: "Full day exploring the crater floor",
//         highSeasonCost: calculatePercentage("250+18%"),
//         lowSeasonCost: calculatePercentage("250+18%"),
//         childHighSeasonCost: 0,
//         childLowSeasonCost: 0,
//       },
//       {
//         id: "ngorongoro-hiking",
//         name: "Crater Rim Hike",
//         description: "Guided hike along the crater rim",
//         highSeasonCost: calculatePercentage("60+18%"),
//         lowSeasonCost: calculatePercentage("30+18%"),
//         childHighSeasonCost: calculatePercentage("20+18%"),
//         childLowSeasonCost: calculatePercentage("10+18%"),
//       },
//     ],
//   },
//   {
//     id: "tarangire",
//     name: "Tarangire National Park",
//     description: "Known for its elephant migration and baobab trees",
//     activities: [
//       {
//         id: "tarangire-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive focusing on elephants",
//         highSeasonCost: calculatePercentage("50+18%"),
//         lowSeasonCost: calculatePercentage("50+18%"),
//         childHighSeasonCost: calculatePercentage("15+18%"),
//         childLowSeasonCost: calculatePercentage("15+18%"),
//       },
//       {
//         id: "tarangire-night-safari",
//         name: "Night Safari",
//         description: "Evening game drive to spot nocturnal animals",
//         highSeasonCost: 130,
//         lowSeasonCost: 100,
//         childHighSeasonCost: 65,
//         childLowSeasonCost: 50,
//       },
//     ],
//   },
//   {
//     id: "arusha",
//     name: "Arusha National Park",
//     description: "Known for its elephant migration and baobab trees",
//     activities: [
//       {
//         id: "arusha-game-drive",
//         name: "Game Drive",
//         description: "Full day game drive focusing on elephants",
//         highSeasonCost: calculatePercentage("50+18%"),
//         lowSeasonCost: calculatePercentage("50+18%"),
//         childHighSeasonCost: calculatePercentage("15+18%"),
//         childLowSeasonCost: calculatePercentage("15+18%"),
//       },
//       {
//         id: "arusha-night-safari",
//         name: "Night Safari",
//         description: "Evening game drive to spot nocturnal animals",
//         highSeasonCost: 130,
//         lowSeasonCost: 100,
//         childHighSeasonCost: 65,
//         childLowSeasonCost: 50,
//       },
//     ],
//   },
//   {
//     id: "lake-manyara",
//     name: "Lake Manyara National Park",
//     description: "Famous for tree-climbing lions and flamingos",
//     activities: [
//       {
//         id: "manyara-game-drive",
//         name: "Game Drive",
//         description: "Half day game drive around the lake",
//         highSeasonCost: calculatePercentage("50+18%"),
//         lowSeasonCost: calculatePercentage("50+18%"),
//         childHighSeasonCost: calculatePercentage("15+18%"),
//         childLowSeasonCost: calculatePercentage("15+18%"),
//       },
//       {
//         id: "manyara-canoe",
//         name: "Canoe Safari",
//         description: "Canoe trip on Lake Manyara",
//         highSeasonCost: 110,
//         lowSeasonCost: 85,
//         childHighSeasonCost: 55,
//         childLowSeasonCost: 42.5,
//       },
//     ],
//   },
//   {
//     id: "mikumi",
//     name: "Mikumi National Park",
//     description: "Famous for tree-climbing lions and flamingos",
//     activities: [
//       {
//         id: "mikumi_game_drive",
//         name: "Game Drive",
//         description: "Half day game drive around the lake",
//         highSeasonCost: calculatePercentage("30+18%"),
//         lowSeasonCost: calculatePercentage("30+18%"),
//         childHighSeasonCost: calculatePercentage("10+18%"),
//         childLowSeasonCost: calculatePercentage("10+18%"),
//       },
//     ],
//   },
//   {
//     id: "zanzibar",
//     name: "Zanzibar Island",
//     description: "Beautiful beaches and historic Stone Town",
//     activities: [
//       {
//         id: "zanzibar-beach",
//         name: "Beach Day",
//         description: "Relaxing day at the beach with snorkeling",
//         highSeasonCost: 0,
//         lowSeasonCost: 0,
//         childHighSeasonCost: 0,
//         childLowSeasonCost: 0,
//       },
//       {
//         id: "zanzibar-stone-town",
//         name: "Stone Town Tour",
//         description: "Guided tour of historic Stone Town",
//         highSeasonCost: 50,
//         lowSeasonCost: 50,
//         childHighSeasonCost: 40,
//         childLowSeasonCost: 30,
//       },
//       {
//         id: "zanzibar-spice-tour",
//         name: "Spice Tour",
//         description: "Visit local spice farms and plantations",
//         highSeasonCost: 35,
//         lowSeasonCost: 35,
//         childHighSeasonCost: 35,
//         childLowSeasonCost: 25,
//       },
//       {
//         id: "zanzibar-snorking-boat",
//         name: "Snorking, Boat Ride",
//         description: "Visit local spice farms and plantations",
//         highSeasonCost: 50,
//         lowSeasonCost: 50,
//         childHighSeasonCost: 35,
//         childLowSeasonCost: 25,
//       },
//       {
//         id: "nungwi-beach",
//         name: "Tortoise Sanctuary, Sandbank Picnic",
//         description: "Visit local spice farms and plantations",
//         highSeasonCost: 55,
//         lowSeasonCost: 55,
//         childHighSeasonCost: 35,
//         childLowSeasonCost: 25,
//       },
//     ],
//   },
// ];

// export const ACCOMMODATIONS: Accommodation[] = [
//   {
//     id: "osero-serengeti-camp", // Done
//     name: "Osero Serengeti Camp",
//     description: "5-star lodge with panoramic views of the plains",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "osero-serengeti-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 100,
//         lowSeasonCost: 100,
//       },
//       {
//         id: "osero-serengeti-double",
//         name: "Double/Twin Room",
//         maxOccupancy: 2,
//         highSeasonCost: 200,
//         lowSeasonCost: 200,
//       },
//       {
//         id: "osero-serengeti-triple",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 300,
//         lowSeasonCost: 300,
//       },
//     ],
//   },
//   {
//     id: "osupuko-tented-camp", //Done
//     name: "Osopuko Tented Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "osupuko-tented-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 101,
//         lowSeasonCost: 101,
//       },
//       {
//         id: "osupuko-tented-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 202,
//         lowSeasonCost: 202,
//       },
//       {
//         id: "osupuko-tented-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 303,
//         lowSeasonCost: 303,
//       },
//     ],
//   },
//   {
//     id: "public-camp-site", //Done
//     name: "Public Camp Site",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "serengeti-heritage-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 35,
//         lowSeasonCost: 35,
//       },
//     ],
//   },
//   {
//     id: "serengeti-heritage-camp", //Done
//     name: "Serengeti Heritage Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "serengeti-heritage-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 270,
//         lowSeasonCost: 270,
//       },
//       {
//         id: "serengeti-heritage-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 540,
//         lowSeasonCost: 540,
//       },
//       {
//         id: "serengeti-heritage-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 750,
//         lowSeasonCost: 750,
//       },
//     ],
//   },

//   {
//     id: "nyota-luxury-tented-camp", //Done
//     name: "Nyoa Luxury Tented Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "nyota-luxury-tented-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 350,
//         lowSeasonCost: 350,
//       },
//       {
//         id: "nyota-luxury-tented-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 630,
//         lowSeasonCost: 630,
//       },
//       {
//         id: "nyota-luxury-tented-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 945,
//         lowSeasonCost: 945,
//       },
//     ],
//   },
//   {
//     id: "sero-camp", //Done
//     name: "Sero Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "sero-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 150,
//         lowSeasonCost: 150,
//       },
//       {
//         id: "sero-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 300,
//         lowSeasonCost: 300,
//       },
//       {
//         id: "sero-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 450,
//         lowSeasonCost: 450,
//       },
//     ],
//   },
//   {
//     id: "african-safari-ikoma-camp", //Done
//     name: "African Safari Ikoma Tented Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["serengeti", "masai-mara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "african-safari-ikoma-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 100,
//         lowSeasonCost: 100,
//       },
//       {
//         id: "african-safari-ikoma-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 200,
//         lowSeasonCost: 200,
//       },
//       {
//         id: "african-safari-ikoma-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 300,
//         lowSeasonCost: 300,
//       },
//     ],
//   },
//   {
//     id: "tarangire-sopa-lodge", //Done
//     name: "Tarangire Sopa Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["tarangire"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "tarangire-sopa-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 269,
//         lowSeasonCost: 234,
//       },
//       {
//         id: "tarangire-sopa-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 414,
//         lowSeasonCost: 361,
//       },
//       {
//         id: "tarangire-sopa-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 527,
//         lowSeasonCost: 460,
//       },
//     ],
//   },
//   {
//     id: "masai-mara-sopa-lodge", //Done
//     name: "Masai Mara Sopa Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["masai-mara"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "masai-mara-sopa-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 239,
//         lowSeasonCost: 154,
//       },
//       {
//         id: "masai-mara-sopa-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 368,
//         lowSeasonCost: 237,
//       },
//       {
//         id: "masai-mara-sopa-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 470,
//         lowSeasonCost: 302,
//       },
//     ],
//   },
//   {
//     id: "lake-nakuru-sopa-lodge", //Done
//     name: "Lake Nakuru Sopa Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["lake-nakuru"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "lake-nakuru-sopa-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 224,
//         lowSeasonCost: 154,
//       },
//       {
//         id: "lake-nakuru-sopa-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 345,
//         lowSeasonCost: 237,
//       },
//       {
//         id: "lake-nakuru-sopa-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 440,
//         lowSeasonCost: 302,
//       },
//     ],
//   },
//   {
//     id: "lake-naivasha-sopa-lodge", //Done
//     name: "Lake Naivasha Sopa Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["lake-naivasha", "nakuru"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "lake-naivasha-sopa-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 268,
//         lowSeasonCost: 204,
//       },
//       {
//         id: "lake-naivasha-sopa-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 413,
//         lowSeasonCost: 314,
//       },
//       {
//         id: "lake-naivasha-sopa-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 526,
//         lowSeasonCost: 400,
//       },
//     ],
//   },
//   {
//     id: "amboseli-sopa-standard-lodge", //Done
//     name: "Amboseli Sopa Standard Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["amboseli"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "amboseli-sopa-standard-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 153,
//         lowSeasonCost: 140,
//       },
//       {
//         id: "amboseli-sopa-standard-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 235,
//         lowSeasonCost: 216,
//       },
//       {
//         id: "amboseli-sopa-standard-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 300,
//         lowSeasonCost: 275,
//       },
//     ],
//   },
//   {
//     id: "amboseli-sopa-premium-lodge", //Done
//     name: "Amboseli Sopa Premium Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["amboseli"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "amboseli-sopa-premium-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 160,
//         lowSeasonCost: 147,
//       },
//       {
//         id: "amboseli-sopa-premium-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 246,
//         lowSeasonCost: 226,
//       },
//       {
//         id: "amboseli-sopa-premium-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 313,
//         lowSeasonCost: 288,
//       },
//     ],
//   },
//   {
//     id: "samburu-sopa-lodge", //Done
//     name: "Samburu Sopa Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["samburu", "shaba", "buffalo-springs"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "samburu-sopa-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 146,
//         lowSeasonCost: 140,
//       },
//       {
//         id: "samburu-sopa-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 224,
//         lowSeasonCost: 216,
//       },
//       {
//         id: "samburu-sopa-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 286,
//         lowSeasonCost: 275,
//       },
//     ],
//   },
//   {
//     id: "jambo-mara-wooden-cottage-lodge", //Done
//     name: "Jambo Mara Wooden Cottage Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["masai-mara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "jambo-mara-wooden-cottage-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 180,
//         lowSeasonCost: 95,
//       },
//       {
//         id: "jambo-mara-wooden-cottage-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 240,
//         lowSeasonCost: 140,
//       },
//     ],
//   },
//   {
//     id: "jambo-mara-glass-cottage-lodge", //Done
//     name: "Jambo Mara Glass Cottage Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["masai-mara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "jambo-mara-glass-cottage-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 220,
//         lowSeasonCost: 115,
//       },
//       {
//         id: "jambo-mara-glass-cottage-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 330,
//         lowSeasonCost: 170,
//       },
//       {
//         id: "jambo-mara-glass-cottage-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 495,
//         lowSeasonCost: 255,
//       },
//     ],
//   },
//   {
//     id: "jambo-mara-superior-delux-lodge", //Done
//     name: "Jambo Mara Superior Delux Lodge",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["masai-mara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "jambo-mara-superior-delux-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 260,
//         lowSeasonCost: 200,
//       },
//       {
//         id: "jambo-mara-superior-delux-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 380,
//         lowSeasonCost: 300,
//       },
//       {
//         id: "jambo-mara-superior-delux-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 570,
//         lowSeasonCost: 450,
//       },
//     ],
//   },
//   {
//     id: "sentrim-mara-camp", //Done
//     name: "Sentrim Mara Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["masai-mara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "sentrim-mara-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 154,
//         lowSeasonCost: 120,
//       },
//       {
//         id: "sentrim-mara-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 253,
//         lowSeasonCost: 220,
//       },
//       {
//         id: "sentrim-mara-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 310,
//         lowSeasonCost: 275,
//       },
//     ],
//   },
//   {
//     id: "sentrim-amboseli-camp", //Done
//     name: "Sentrim Amboseli Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["amboseli"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "sentrim-amboseli-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 145,
//         lowSeasonCost: 120,
//       },
//       {
//         id: "sentrim-amboseli-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 230,
//         lowSeasonCost: 210,
//       },
//       {
//         id: "sentrim-amboseli-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 300,
//         lowSeasonCost: 264,
//       },
//     ],
//   },
//   {
//     id: "sentrim-tsavo-camp", //Done
//     name: "Sentrim Tsavo Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["tsavo-east", "tsavo-west"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "sentrim-tsavo-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 132,
//         lowSeasonCost: 110,
//       },
//       {
//         id: "sentrim-tsavo-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 220,
//         lowSeasonCost: 200,
//       },
//       {
//         id: "sentrim-tsavo-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 264,
//         lowSeasonCost: 242,
//       },
//     ],
//   },
//   {
//     id: "sentrim-elementaita-camp", //Done
//     name: "Sentrim Elementaita Camp",
//     description: "Authentic safari experience with comfortable tents",
//     location: ["elementaita", "nakuru"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "sentrim-elementaita-camp-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 145,
//         lowSeasonCost: 120,
//       },
//       {
//         id: "sentrim-elementaita-camp-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 220,
//         lowSeasonCost: 198,
//       },
//       {
//         id: "sentrim-elementaita-camp-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 286,
//         lowSeasonCost: 255,
//       },
//     ],
//   },
//   {
//     id: "eileens-tree-inn", //Done
//     name: "Eileen's Trees Inn",
//     description: "Luxury lodge on the crater rim with stunning views",
//     location: ["ngorongoro", "tarangire", "lake-manyara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "eileens-tree-inn-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 70,
//         lowSeasonCost: 70,
//       },
//       {
//         id: "eileens-tree-inn-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 140,
//         lowSeasonCost: 140,
//       },
//       {
//         id: "eileens-tree-inn-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 210,
//         lowSeasonCost: 210,
//       },
//     ],
//   },
//   {
//     id: "farm-of-dreams-lodge", //Done
//     name: "Farm of Dreams Lodge",
//     description: "Colonial-style farm house with beautiful gardens",
//     location: ["ngorongoro", "tarangire", "lake-manyara"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "farm-of-dreams-lodge-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 100,
//         lowSeasonCost: 100,
//       },
//       {
//         id: "farm-of-dreams-lodge-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 195,
//         lowSeasonCost: 195,
//       },
//       {
//         id: "farm-of-dreams-lodge-triple",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 273,
//         lowSeasonCost: 273,
//       },
//     ],
//   },
//   {
//     id: "ngare-lodge", //Done
//     name: "Ngare Sero Mountain Lodge",
//     description: "Colonial-style farm house with beautiful gardens",
//     location: ["lake-manyara", "ngorongoro", "tarangire"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "ngare-lodge-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 45,
//         lowSeasonCost: 45,
//       },
//       {
//         id: "ngare-lodge-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 90,
//         lowSeasonCost: 90,
//       },
//       {
//         id: "ngare-lodge-triple",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 135,
//         lowSeasonCost: 135,
//       },
//     ],
//   },
//   {
//     id: "green-mountain-lodge", //Done
//     name: "Green Mountain Lodge",
//     description: "Unique rooms built into baobab trees",
//     location: ["Arusha"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "green-mountain-lodge-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 300,
//         lowSeasonCost: 240,
//       },
//       {
//         id: "green-mountain-lodge-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 380,
//         lowSeasonCost: 300,
//       },
//       {
//         id: "green-mountain-lodge-family",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 600,
//         lowSeasonCost: 480,
//       },
//     ],
//   },
//   {
//     id: "marera-valley-lodge", //Done
//     name: "Marera Valley Lodge",
//     description: "Lodge overlooking Lake Manyara and the Rift Valley",
//     location: ["karatu", "lake-manyara", "ngorongoro", "tarangire"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "marera-valley-lodge-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 100,
//         lowSeasonCost: 100,
//       },
//       {
//         id: "marera-valley-lodge-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 191,
//         lowSeasonCost: 191,
//       },
//       {
//         id: "marera-valley-lodge-triple",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 300,
//         lowSeasonCost: 300,
//       },
//     ],
//   },
//   {
//     id: "neptune-ngorongoro-luxury-lodge", //Done
//     name: "Neptune Ngorongoro Luxury Lodge",
//     description: "Beachfront resort with white sand beaches",
//     location: ["Ngorongoro"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "neptune-ngorongoro-luxury-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 444,
//         lowSeasonCost: 444,
//       },
//       {
//         id: "neptune-ngorongoro-luxury-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 867,
//         lowSeasonCost: 867,
//       },
//       {
//         id: "neptune-ngorongoro-luxury-triple",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 1300,
//         lowSeasonCost: 1300,
//       },
//     ],
//   },
//   {
//     id: "lila-tanzania-lodge", //Done
//     name: "Lilac Tanzania Hotel",
//     description: "Historic hotel in the heart of Stone Town",
//     location: ["karatu", "lake-manyara", "ngorongoro", "tarangire"],
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "lila-tanzania-lodge-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 35,
//         lowSeasonCost: 35,
//       },
//       {
//         id: "lila-tanzania-lodge-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 70,
//         lowSeasonCost: 70,
//       },
//       {
//         id: "lila-tanzania-lodge-triple",
//         name: "Triple Room",
//         maxOccupancy: 3,
//         highSeasonCost: 105,
//         lowSeasonCost: 105,
//       },
//     ],
//   },
//   {
//     id: "arusha-mountain-lodge",
//     name: "Arusha Mountain Lodge",
//     description: "Cozy lodge with views of Mount Meru",
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "arusha-mountain-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 210,
//         lowSeasonCost: 170,
//       },
//       {
//         id: "arusha-mountain-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 270,
//         lowSeasonCost: 210,
//       },
//       {
//         id: "arusha-mountain-family",
//         name: "Family Room",
//         maxOccupancy: 4,
//         highSeasonCost: 420,
//         lowSeasonCost: 330,
//       },
//     ],
//   },
//   {
//     id: "africa-safari-lake-manyara",
//     name: "Africa Safari Lake Manyara",
//     description: "Cozy lodge with views of Mount Meru",
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "africa-safari-lake-manyara-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 210,
//         lowSeasonCost: 170,
//       },
//       {
//         id: "africa-safari-lake-manyara-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 270,
//         lowSeasonCost: 210,
//       },
//       {
//         id: "africa-safari-lake-manyara-family",
//         name: "Family Room",
//         maxOccupancy: 4,
//         highSeasonCost: 420,
//         lowSeasonCost: 330,
//       },
//     ],
//   },
//   {
//     id: "serengeti-heritage-camp",
//     name: "Serengeti Heritage Camp",
//     description: "Cozy lodge with views of Mount Meru",
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       {
//         id: "serengeti-heritage-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 140,
//         lowSeasonCost: 140,
//       },
//       {
//         id: "serengeti-heritage-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 270,
//         lowSeasonCost: 270,
//       },
//       {
//         id: "serengeti-heritage-family",
//         name: "Family Room",
//         maxOccupancy: 4,
//         highSeasonCost: 375,
//         lowSeasonCost: 375,
//       },
//     ],
//   },
//   {
//     id: "bustian-camp-mikumi",
//     name: "Camp Bustian Mikumi",
//     description: "Cozy lodge with views of Mount Meru",
//     includesFullBoard: true,
//     inPark: false,
//     roomTypes: [
//       {
//         id: "bustian-camp-mikumi-single",
//         name: "Single Room",
//         maxOccupancy: 1,
//         highSeasonCost: 60,
//         lowSeasonCost: 60,
//       },
//       {
//         id: "bustian-camp-mikumi-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 120,
//         lowSeasonCost: 120,
//       },
//       {
//         id: "bustian-camp-mikumi-family",
//         name: "Family Room",
//         maxOccupancy: 4,
//         highSeasonCost: 375,
//         lowSeasonCost: 375,
//       },
//     ],
//   },
//   {
//     id: "tembo-house-hotel",
//     name: "Tembo House Hotel",
//     description: "Cozy lodge with views of Mount Meru",
//     location: ["zanzibar"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       // {
//       //   id: "serengeti-heritage-single",
//       //   name: "Single Room",
//       //   maxOccupancy: 1,
//       //   highSeasonCost: 140,
//       //   lowSeasonCost: 140,
//       // },
//       {
//         id: "serengeti-heritage-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 75,
//         lowSeasonCost: 75,
//       },
//       // {
//       //   id: "serengeti-heritage-family",
//       //   name: "Family Room",
//       //   maxOccupancy: 4,
//       //   highSeasonCost: 375,
//       //   lowSeasonCost: 375,
//       // },
//     ],
//   },
//   {
//     id: "sunshine-hotel",
//     name: "Sunshine Hotel",
//     description: "Cozy lodge with views of Mount Meru",
//     location: ["zanzibar"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       // {
//       //   id: "serengeti-heritage-single",
//       //   name: "Single Room",
//       //   maxOccupancy: 1,
//       //   highSeasonCost: 140,
//       //   lowSeasonCost: 140,
//       // },
//       {
//         id: "serengeti-heritage-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 120,
//         lowSeasonCost: 120,
//       },
//       // {
//       //   id: "serengeti-heritage-family",
//       //   name: "Family Room",
//       //   maxOccupancy: 4,
//       //   highSeasonCost: 375,
//       //   lowSeasonCost: 375,
//       // },
//     ],
//   },
//   {
//     id: "sunset-kendwa",
//     name: "Sunset Kendwa",
//     description: "Zanzibar beachfront resort with white sand beaches",
//     location: ["zanzibar"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       // {
//       //   id: "serengeti-heritage-single",
//       //   name: "Single Room",
//       //   maxOccupancy: 1,
//       //   highSeasonCost: 140,
//       //   lowSeasonCost: 140,
//       // },
//       {
//         id: "sunset-kendwa-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 120,
//         lowSeasonCost: 120,
//       },
//       // {
//       //   id: "serengeti-heritage-family",
//       //   name: "Family Room",
//       //   maxOccupancy: 4,
//       //   highSeasonCost: 375,
//       //   lowSeasonCost: 375,
//       // },
//     ],
//   },
//   {
//     id: "aluna-beach-hotel",
//     name: "Aluna Beach Hotel",
//     description: "Zanzibar beachfront resort with white sand beaches",
//     location: ["zanzibar"],
//     includesFullBoard: true,
//     inPark: true,
//     roomTypes: [
//       // {
//       //   id: "serengeti-heritage-single",
//       //   name: "Single Room",
//       //   maxOccupancy: 1,
//       //   highSeasonCost: 140,
//       //   lowSeasonCost: 140,
//       // },
//       {
//         id: "aluna-beach-hotel-double",
//         name: "Double Room",
//         maxOccupancy: 2,
//         highSeasonCost: 150,
//         lowSeasonCost: 150,
//       },
//       // {
//       //   id: "serengeti-heritage-family",
//       //   name: "Family Room",
//       //   maxOccupancy: 4,
//       //   highSeasonCost: 375,
//       //   lowSeasonCost: 375,
//       // },
//     ],
//   },
// ];

// export const CONCESSION_FEE = calculatePercentage("50+18%"); // $60 per person
// export const CHILD_CONCESSION_FEE = calculatePercentage("10+18%"); // $30 per child
// export const VEHICLE_CAPACITY = 7; // Each vehicle can carry 7 clients
